### ISSUE TITLE
Use STARK friendly hash functions for proof commitments

### ISSUE THREAD

**Issue by andrewmilson** [andrewmilson/ministark#11]
Supporting STARK friendly hash functions for proof commitments will be a great step forward to supporting recursive STARKs. miniSTARK uses RustCrypto's [Digest trait](https://docs.rs/digest/latest/digest/trait.Digest.html) as an interface for hash functions.

**Comment by andrewmilson** [comment]
Hash interfaces are generic now. See [this](https://github.com/andrewmilson/sandstorm/blob/main/crypto/src/merkle/mod.rs#L43) Sandstorm example of a merkle tree that has some Pedersen layers and some blake2s layers

**Comment by pad01g** [comment]
@andrewmilson 
In above example, it seems like blake2s and keccak256 are both masked so that they only have 80 bits of  security. Is it speed-up technique for recursive computation, or do you have any other intention there?
