### ISSUE TITLE
Support keccak hash

### ISSUE THREAD

**Issue by sidhujag** [andrewmilson/ministark#14]
In Syscoin we create blobs (like EIP4844) using quantum resistant, no trusted-setup (keccak hash based) transactions carrying blob data that gets pruned after a finality checkpoint + 6 hours. In hermez zkevm we noticed for now they are able to perform their circuit input checks via the keccak hash (as standardization for using the EVM). Perhaps you can also include this as a standardization effort to integrate into EVM applications such as zkRollups? We do not plan to use KZG commitments like Ethereum due to their need for trusted setup, not being quantum safe and also because we do not shard the data, every node checks the entire blob and stores the entire blob until pruning (which we view as the only way to do this in a decentralized way).

**Comment by andrewmilson** [comment]
miniSTARK supports keccak now. See [this Sandstorm example](https://github.com/andrewmilson/sandstorm/blob/main/src/claims.rs#L18) which was used to submit a proof to StarkWare's verifier.
